import {chromium} from 'playwright';import fs from 'node:fs';
const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce',timezoneId:'America/Los_Angeles'});p.setDefaultTimeout(7000);
const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const ok=(name,pass)=>{checks.push({name,passed:!!pass});if(!pass)throw Error(name)};
const go=async q=>{await p.goto('https://frontx.constructor.rocks/?'+q);await p.locator('h1').first().waitFor();await p.evaluate(()=>document.fonts.ready)};
const dialog=()=>p.getByRole('dialog');const pick=(name)=>dialog().getByRole('button',{name});
try {
 await go('page=date-picker');await p.locator('.date-picker-inline .date-dropdown').first().waitFor();await p.screenshot({path:'qa/release-2026-10-05-date-picker/desktop.png',fullPage:true});
 const inline=p.locator('.date-picker-inline');await inline.getByRole('combobox',{name:'Choose the Year'}).selectOption('1990');await inline.getByRole('combobox',{name:'Choose the Month'}).selectOption('1');await inline.getByRole('button',{name:/February 14th, 1990/}).click();ok('far-past inline date takes direct year/month/day selections',new URL(p.url()).searchParams.get('pickDate')==='1990-02-14');
 await p.getByRole('button',{name:'Choose date',exact:true}).click();await dialog().waitFor();ok('single popup opens at selected date',await dialog().getByRole('grid',{name:'February 1990'}).isVisible());
 await dialog().getByRole('combobox',{name:'Choose the Year'}).selectOption('2050');await dialog().getByRole('combobox',{name:'Choose the Month'}).selectOption('11');await pick(/December 25th, 2050/).click();await dialog().waitFor({state:'hidden'});ok('future year available without month paging',new URL(p.url()).searchParams.get('pickDate')==='2050-12-25');ok('inline follows external selection month',await inline.getByRole('grid',{name:'December 2050'}).isVisible());ok('single selection returns focus',await p.getByRole('button',{name:'Choose date',exact:true}).evaluate(e=>e===document.activeElement));
 await p.goBack();await inline.getByRole('grid',{name:'February 1990'}).waitFor();ok('Back restores inline month and value',new URL(p.url()).searchParams.get('pickDate')==='1990-02-14');
 await go('page=date-picker');await p.getByRole('button',{name:'Choose date',exact:true}).focus();await p.keyboard.press('Enter');await dialog().waitFor();ok('popup focuses selected day',await p.evaluate(()=>document.activeElement?.getAttribute('aria-label')?.includes('October 5th')));await p.keyboard.press('ArrowRight');await p.keyboard.press('Enter');await dialog().waitFor({state:'hidden'});ok('date grid keyboard selects next day',new URL(p.url()).searchParams.get('pickDate')==='2026-10-06');
 await p.getByRole('button',{name:'Choose date range',exact:true}).click();await dialog().waitFor();ok('desktop range shows two months',await dialog().getByRole('grid').count()===2);await dialog().getByRole('button',{name:'Clear',exact:true}).click();ok('clear inside popup resets host range',new URL(p.url()).searchParams.get('pickFrom')==='none');ok('empty range cannot finish',await dialog().getByRole('button',{name:'Done',exact:true}).isDisabled());await dialog().getByRole('grid').first().getByRole('button',{name:/October 7th, 2026/}).click();ok('range start remains open and incomplete',await dialog().isVisible()&&await dialog().getByRole('button',{name:'Done',exact:true}).isDisabled());await dialog().getByRole('grid').first().getByRole('button',{name:/October 12th, 2026/}).click();ok('range selection retained',new URL(p.url()).searchParams.get('pickTo')==='2026-10-12');await p.screenshot({path:'qa/release-2026-10-05-date-picker/range.png'});await dialog().getByRole('button',{name:'Done',exact:true}).click();await dialog().waitFor({state:'hidden'});ok('Done returns focus to range field',await p.getByRole('button',{name:'Choose date range',exact:true}).evaluate(e=>e===document.activeElement));
 await p.getByRole('button',{name:'Choose date range',exact:true}).click();await dialog().waitFor();await p.setViewportSize({width:390,height:844});await p.waitForFunction(()=>document.querySelectorAll('[role=dialog] [role=grid]').length===1);ok('live resize preserves complete range',new URL(p.url()).searchParams.get('pickTo')==='2026-10-12');await p.screenshot({path:'qa/release-2026-10-05-date-picker/mobile-popup.png'});
 for(const width of [320,390]){await p.setViewportSize({width,height:844});await p.waitForFunction(()=>{const e=document.querySelector('[role=dialog]');const r=e?.getBoundingClientRect();return r&&r.x>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1});ok(`${width} popup bounds`,await dialog().evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1}));ok(`${width} date targets meet 24px minimum`,await dialog().locator('.date-day button').first().evaluate(e=>{const r=e.getBoundingClientRect();return r.width>=24&&r.height>=24}));}
 await p.keyboard.press('Escape');await p.locator('h1').click();await p.evaluate(()=>scrollTo(0,0));ok('320 page bounds',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'qa/release-2026-10-05-date-picker/mobile.png',fullPage:true});
 await p.setViewportSize({width:1440,height:1000});for(const theme of ['fabric','editorial','terminal','iris','lagoon'])for(const mode of ['light','dark']){await go(`page=date-picker&theme=${theme}&mode=${mode}`);await p.getByRole('button',{name:'Choose date range',exact:true}).click();await dialog().waitFor();ok(`${theme}/${mode} selection and year controls`,await dialog().getByRole('combobox',{name:'Choose the Year'}).count()===2&&await dialog().getByRole('gridcell',{selected:true}).count()>0);await p.screenshot({path:`qa/release-2026-10-05-date-picker/${theme}-${mode}.png`});await p.keyboard.press('Escape');}
 await go('page=event-calendar&calTab=playground&calDate=2026-10-05&calView=week');await p.locator('.cal-date-title').click();await p.getByRole('dialog',{name:'Choose calendar date'}).waitFor();await dialog().getByRole('combobox',{name:'Choose the Year'}).selectOption('2035');await dialog().getByRole('combobox',{name:'Choose the Month'}).selectOption('2');await dialog().getByRole('button',{name:/March 12th, 2035/}).click();await dialog().waitFor({state:'hidden'});ok('event calendar direct year/month/day jump',new URL(p.url()).searchParams.get('calDate')==='2035-03-12');
 await go('page=event-calendar&calTab=playground&calDate=2026-10-05&calView=week');await p.setViewportSize({width:390,height:844});const newEvent=p.getByRole('button',{name:'New event',exact:true});ok('mobile populated agenda has visible creation action',await newEvent.isVisible());await newEvent.click();await p.getByLabel('Title',{exact:true}).fill('Audit keyboard event');await p.getByRole('dialog',{name:'Create event',exact:true}).getByLabel('Timezone',{exact:true}).locator('option[value="America/Los_Angeles"]').waitFor({state:'attached'});ok('editor includes browser local timezone',await p.getByLabel('Timezone',{exact:true}).locator('option[value="America/Los_Angeles"]').count()===1);await p.keyboard.press('Escape');await p.getByRole('alertdialog').waitFor();await p.waitForFunction(()=>document.activeElement?.textContent==='Keep editing');ok('discard focuses safe Keep editing action',await p.getByRole('button',{name:'Keep editing',exact:true}).evaluate(e=>e===document.activeElement));for(let i=0;i<5;i++){await p.keyboard.press('Tab');await p.waitForFunction(()=>!!document.activeElement?.closest('[role=alertdialog]'));ok(`discard focus trapped ${i+1}`,await p.getByRole('alertdialog').evaluate(e=>e.contains(document.activeElement)));}await p.getByRole('button',{name:'Keep editing',exact:true}).click();ok('keep editing retains draft',await p.getByLabel('Title',{exact:true}).inputValue()==='Audit keyboard event');await p.getByRole('button',{name:'Cancel',exact:true}).click();await p.getByRole('button',{name:'Discard changes',exact:true}).click();
 ok('no browser errors',errors.length===0);console.log(JSON.stringify({passed:checks.length,errors}));
}catch(e){console.error(e);await p.screenshot({path:'qa/release-2026-10-05-date-picker/failure.png'});process.exitCode=1}finally{fs.writeFileSync('qa/release-2026-10-05-date-picker/report.json',JSON.stringify({checks,errors,at:new Date().toISOString()},null,2));await b.close()}
