import {chromium} from 'playwright';import fs from 'node:fs';
const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});p.setDefaultTimeout(6000);const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const ok=(name,pass)=>{checks.push({name,passed:!!pass});if(!pass)throw Error(name)};const url='http://127.0.0.1:5202';const go=async(q)=>{await p.goto(`${url}/?${q}`);await p.locator('h1').first().waitFor();await p.evaluate(()=>document.fonts.ready)};const day=n=>p.getByRole('dialog').getByRole('grid').first().getByRole('button').filter({hasText:new RegExp(`^${n}$`)});
try{
 await go('page=date-picker');ok('nav order', (await p.locator('.sidebar .site-side-link').allTextContents()).slice(0,3).join('|')==='Charts & widgets|Event calendar|Date picker');
 await p.getByRole('button',{name:'Choose date',exact:true}).focus();await p.keyboard.press('Enter');await p.getByRole('dialog').waitFor();const selected=p.getByRole('dialog').getByRole('button',{name:/October 5th.*selected/});await selected.focus();await p.keyboard.press('ArrowRight');await p.keyboard.press('Enter');await p.getByRole('dialog').waitFor({state:'hidden'});ok('single keyboard selection',new URL(p.url()).searchParams.get('pickDate')==='2026-10-06');ok('popup returns focus',await p.getByRole('button',{name:'Choose date',exact:true}).evaluate(e=>e===document.activeElement));await p.evaluate(()=>history.back());await p.waitForFunction(()=>new URL(location.href).searchParams.get('pickDate')===null);ok('Back restores date', (await p.getByRole('button',{name:'Choose date',exact:true}).innerText()).includes('5th'));
 await p.getByRole('button',{name:'Clear date',exact:true}).click();ok('clear single',await p.getByRole('button',{name:'Clear date',exact:true}).isDisabled());await p.getByRole('grid').getByRole('button',{name:/October 8th/}).click();ok('inline date updates field',new URL(p.url()).searchParams.get('pickDate')==='2026-10-08');
 await p.getByRole('button',{name:'Clear range',exact:true}).click();await p.getByRole('button',{name:'Choose date range',exact:true}).click();ok('desktop has two months',await p.getByRole('dialog').getByRole('grid').count()===2);await day(7).click();await day(12).click();ok('trip range selected',new URL(p.url()).searchParams.get('pickFrom')==='2026-10-07'&&new URL(p.url()).searchParams.get('pickTo')==='2026-10-12');await p.screenshot({path:'qa/component-handoff/range-desktop.png'});
 await p.setViewportSize({width:390,height:844});await p.waitForFunction(()=>document.querySelectorAll('[role=dialog] [role=grid]').length===1);ok('open range adapts without losing dates',new URL(p.url()).searchParams.get('pickTo')==='2026-10-12');ok('mobile popup fits',await p.getByRole('dialog').evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth&&r.height<=innerHeight}));await p.getByRole('dialog').getByRole('button',{name:'Go to the Next Month',exact:true}).click();await p.getByRole('dialog').getByRole('grid',{name:'November 2026'}).waitFor();ok('mobile browses next month',true);await p.keyboard.press('Escape');await p.locator('h1').click();await p.evaluate(()=>window.scrollTo(0,0));await p.screenshot({path:'qa/component-handoff/date-mobile.png',fullPage:true});ok('mobile page fits',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.setViewportSize({width:320,height:740});await p.getByRole('button',{name:'Choose date range',exact:true}).click();ok('320px popup fits',await p.getByRole('dialog').evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth+1}));await p.keyboard.press('Escape');
 await p.setViewportSize({width:1440,height:1000});
 for(const theme of ['fabric','editorial','terminal','iris','lagoon'])for(const mode of ['light','dark']){
  await go(`page=date-picker&theme=${theme}&mode=${mode}`);await p.getByRole('button',{name:'Choose date range',exact:true}).click();await p.getByRole('dialog').waitFor();ok(`${theme} ${mode} range selection present`,await p.getByRole('dialog').getByRole('gridcell',{selected:true}).count()>0);await p.screenshot({path:`qa/component-handoff/date-${theme}-${mode}.png`});await p.keyboard.press('Escape');
 }
 await go('page=event-calendar&calTab=preview');await p.locator('.event-calendar').first().waitFor();const tabs=p.getByRole('tablist',{name:'Calendar examples'});ok('calendar uses shared tabs',await tabs.evaluate(e=>e.classList.contains('section-tabs')));await tabs.getByRole('tab',{name:'Preview',exact:true}).focus();await p.keyboard.press('ArrowRight');await p.keyboard.press('Enter');await p.waitForURL(/calTab=playground/);ok('tabs keyboard controls URL',true);await p.getByRole('tab',{name:'Integration',exact:true}).click();await p.getByRole('link',{name:'Download components',exact:true}).waitFor();ok('handoff has archive and guide',await p.getByRole('link',{name:'Integration guide',exact:true}).isVisible());for(const file of ['frontx-calendar-components.zip','EVENT-CALENDAR.md','DATE-PICKER.md','ControlledCalendar.tsx']){const r=await p.request.get(`${url}/handoff/${file}`);ok(`download ${file}`,r.ok()&&(await r.body()).length>150)}await p.screenshot({path:'qa/component-handoff/integration.png'});
 await go('page=widget&widget=bar');ok('chart uses shared tabs',await p.locator('.section-tabs').count()===1);await p.getByRole('tab',{name:'Data',exact:true}).click();ok('chart data opens',await p.getByRole('tabpanel').getByRole('table').count()>0);await p.getByRole('tab',{name:'React',exact:true}).click();ok('chart React opens',await p.getByRole('button',{name:'Copy React',exact:true}).isVisible());await p.screenshot({path:'qa/component-handoff/chart-tabs.png'});
 await go('page=widget&widget=heatmap');await p.getByRole('tab',{name:'Weekly',exact:true}).click();ok('token activity uses shared tabs',await p.getByRole('tablist',{name:'Activity period'}).evaluate(e=>e.classList.contains('section-tabs')));await p.getByRole('tab',{name:'Cumulative',exact:true}).click();ok('activity selection retained',await p.getByRole('tab',{name:'Cumulative',exact:true}).getAttribute('aria-selected')==='true');
 await go('page=elements');await p.getByRole('tab',{name:/Activity/}).click();ok('Elements example uses shared tabs',await p.getByRole('tablist',{name:'Report views'}).evaluate(e=>e.classList.contains('section-tabs')));
 await go('page=event-calendar&calTab=preview');await p.screenshot({path:'qa/component-handoff/calendar-tabs.png'});await p.setViewportSize({width:390,height:844});ok('mobile tabs fit',await p.locator('.section-tabs').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.screenshot({path:'qa/component-handoff/calendar-mobile-tabs.png'});
 await p.setViewportSize({width:1440,height:1000});const requests=[];p.on('request',r=>requests.push(r.url()));await p.goto('http://127.0.0.1:5201/qa/component-handoff/consumer.html');await p.locator('.event-calendar').waitFor();ok('isolated consumer has no Showcase globals',!requests.some(u=>u.includes('/src/style.css')||u.includes('/src/main.tsx')||u.includes('/src/CalendarShowcase')));await p.getByRole('button',{name:'New event',exact:true}).click();await p.getByLabel('Title',{exact:true}).fill('Consumer event');await p.getByRole('button',{name:'Teal',exact:true}).click();await p.getByRole('button',{name:'Create event',exact:true}).click();await p.getByRole('heading',{name:'Consumer event',exact:true}).waitFor();ok('isolated create works',true);await p.keyboard.press('Escape');await p.getByRole('button',{name:'New event',exact:true}).click();await p.getByLabel('Title',{exact:true}).fill('Unsaved consumer');await p.keyboard.press('Escape');await p.getByRole('button',{name:'Keep editing',exact:true}).click();ok('isolated dirty guard works',await p.getByLabel('Title',{exact:true}).inputValue()==='Unsaved consumer');await p.getByRole('button',{name:'Cancel',exact:true}).click();await p.getByRole('button',{name:'Discard changes',exact:true}).click();await p.getByRole('button',{name:'Leave calendar',exact:true}).click();ok('isolated host can leave after guard',await p.locator('.event-calendar').count()===0);await p.getByRole('button',{name:'Open calendar',exact:true}).click();ok('isolated host retains events',await p.locator('[data-event-id]').count()===2);await p.screenshot({path:'qa/component-handoff/isolated.png'});
 ok('no page errors',errors.length===0);console.log(JSON.stringify({passed:checks.length,errors}));
}catch(e){console.error(e);await p.screenshot({path:'qa/component-handoff/failure.png'});process.exitCode=1}finally{fs.writeFileSync('qa/component-handoff/browser-report.json',JSON.stringify({checks,errors,at:new Date().toISOString()},null,2));await b.close()}
