import {chromium} from 'playwright';import fs from 'node:fs';
const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1600,height:1000},reducedMotion:'reduce'});p.setDefaultTimeout(6000);const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const ok=(name,pass)=>{checks.push({name,passed:!!pass});if(!pass)throw Error(name)};
const go=async(q='')=>{await p.goto(`http://127.0.0.1:5202/?page=event-calendar&calTab=playground${q}`);await p.locator('.event-calendar').waitFor();await p.evaluate(()=>document.fonts.ready)};
try{
for(const density of ['standard','compact'])for(const view of ['week','day']){
 await go(`&calDensity=${density}&calView=${view}&calDate=2026-10-09`);
 const heading=p.locator('.cal-day-heading').first();ok(`${density} ${view} date is inline`,await heading.evaluate(el=>{const a=el.querySelector('span').getBoundingClientRect(),b=el.querySelector('strong').getBoundingClientRect();return Math.abs(a.y+a.height/2-b.y-b.height/2)<1}));ok(`${density} ${view} header at most 48px`,(await p.locator('.fc-col-header').boundingBox()).height<=48);
 const event=p.locator('[data-event-id="london"]');await event.scrollIntoViewIfNeeded();ok(`${density} ${view} short event hides time`,await event.locator('.cal-event-time').evaluate(e=>getComputedStyle(e).display==='none'));
 ok(`${density} ${view} short title fits height`,await event.locator('strong').evaluate(e=>{const a=e.getBoundingClientRect(),b=e.closest('.fc-event-main').getBoundingClientRect();return a.height>=16&&a.top>=b.top&&a.bottom<=b.bottom}));
 ok(`${density} ${view} retains accessible time`,(await event.getAttribute('aria-label')).includes('16:00'));
 await event.focus();await p.keyboard.press('Enter');await p.getByRole('heading',{name:'London check-in',exact:true}).waitFor();ok(`${density} ${view} details retain time`,(await p.getByRole('dialog').innerText()).includes('16:00'));await p.keyboard.press('Escape');
 if(view==='week')await p.screenshot({path:`qa/calendar-polish/after-friday-${density}.png`});
 await go(`&calDensity=${density}&calView=${view}&calDate=2026-10-06`);const long=p.locator('[data-event-id="course-test"]');await long.scrollIntoViewIfNeeded();ok(`${density} ${view} tall event keeps time`,await long.locator('.cal-event-time').isVisible());ok(`${density} ${view} tall event text fits`,await long.evaluate(e=>{const a=e.querySelector('strong').getBoundingClientRect(),t=e.querySelector('.cal-event-time').getBoundingClientRect(),b=e.querySelector('.fc-event-main').getBoundingClientRect();return a.bottom<=t.top&&t.bottom<=b.bottom}));
}
await p.goto('http://127.0.0.1:5202/?page=event-calendar');const compact=p.locator('.event-calendar').nth(1);await compact.scrollIntoViewIfNeeded();ok('compact persistent lower inset',await compact.evaluate(e=>{const root=e.getBoundingClientRect(),body=e.querySelector('.cal-body').getBoundingClientRect();return root.bottom-body.bottom>=14}));await p.screenshot({path:'qa/calendar-polish/after-compact.png'});const list=compact.locator('.cal-agenda');await list.evaluate(e=>e.scrollTop=e.scrollHeight);ok('compact last event clears bottom edge',await compact.evaluate(e=>{const items=e.querySelectorAll('.cal-agenda-event');return e.getBoundingClientRect().bottom-items[items.length-1].getBoundingClientRect().bottom>=14}));await compact.locator('[data-event-id="london"]').click();await p.getByRole('heading',{name:'London check-in',exact:true}).waitFor();ok('compact last event opens',true);await p.keyboard.press('Escape');
await p.setViewportSize({width:390,height:844});await p.locator('h1').click();await p.evaluate(()=>window.scrollTo(0,0));ok('mobile no page overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'qa/calendar-polish/mobile.png',fullPage:true});
await p.setViewportSize({width:1600,height:1000});await go('&mode=dark');await p.locator('[data-event-id="london"]').scrollIntoViewIfNeeded();await p.screenshot({path:'qa/calendar-polish/dark.png'});await go('&calView=month');ok('month retains time',await p.locator('[data-event-id="london"] .cal-event-time').isVisible());await p.screenshot({path:'qa/calendar-polish/month.png'});ok('no runtime errors',errors.length===0);console.log(JSON.stringify({passed:checks.length,errors}));
}catch(e){console.error(e);await p.screenshot({path:'qa/calendar-polish/failure.png'});process.exitCode=1}finally{fs.writeFileSync('qa/calendar-polish/report.json',JSON.stringify({checks,errors,at:new Date().toISOString()},null,2));await b.close()}
