import {chromium} from 'playwright';import fs from 'node:fs';
const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000},locale:'en-US',reducedMotion:'reduce'});p.setDefaultTimeout(7000);const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const ok=(name,pass)=>{checks.push({name,passed:!!pass});if(!pass)throw Error(name)};const go=async q=>{await p.goto('http://127.0.0.1:5202/?'+q);await p.locator('h1').first().waitFor();};
try {
 await go('page=date-picker');await p.locator('.date-weekday').first().waitFor();await p.waitForFunction(()=>document.querySelector('.date-weekday')?.textContent==='Sun');ok('browser en-US gives Sunday-first',true);await p.getByRole('button',{name:'Formats',exact:true}).click();const settings=p.getByRole('dialog',{name:'Date and time formats'});await settings.waitFor();ok('system preference resolves browser region',(await settings.locator('output').innerText()).includes('en-US'));ok('US default time is 12-hour',(await settings.locator('output').innerText()).includes('PM'));
 await settings.getByLabel('Region',{exact:true}).selectOption('ru-RU');ok('Russian region sample uses day-first date',(await settings.locator('output').innerText()).includes('05.10.2026'));await p.keyboard.press('Escape');ok('date header localizes month',(await p.locator('.date-picker-inline .date-caption-label').first().innerText()).includes('окт'));ok('regional week starts Monday',(await p.locator('.date-weekday').first().innerText()).includes('пн'));ok('URL retains selected day across region changes',!new URL(p.url()).searchParams.has('pickDate'));await p.screenshot({path:'qa/date-picker-refresh/russian.png',fullPage:true});await p.goBack();await p.waitForFunction(()=>document.querySelector('.date-weekday')?.textContent==='Sun');ok('Back restores regional preference',true);
 for(const [locale,month] of [['en-US','Oct'],['en-GB','Oct'],['de-DE','Okt'],['fr-FR','oct'],['ja-JP','10']]) {await go(`page=date-picker&dateLocale=${locale}`);await p.locator('.date-caption-label').first().waitFor();ok(`${locale} month formatting`,(await p.locator('.date-caption-label').first().innerText()).includes(month));}
 await go('page=event-calendar&calTab=playground&calDate=2026-10-05&calView=week&dateLocale=en-US');await p.locator('.fc-timegrid-slot-label-cushion').first().waitFor();ok('US event grid shows AM/PM',await p.locator('.fc-timegrid-slot-label-cushion').allTextContents().then(x=>x.some(s=>/am|pm/i.test(s))));await p.getByRole('group',{name:'Time grid',exact:true}).focus();ok('keyboard slot uses regional time', /AM|PM/i.test(await p.locator('.cal-slot-status').innerText()));await p.locator('h1').click();ok('US week starts Sunday',await p.locator('.fc-col-header-cell[data-date]').first().getAttribute('data-date')==='2026-10-04');
 await p.getByRole('button',{name:'Formats',exact:true}).click();await settings.getByLabel('Time format',{exact:true}).selectOption('24');await settings.getByLabel('Week starts on',{exact:true}).selectOption('1');await p.keyboard.press('Escape');ok('explicit 24-hour override',await p.locator('.fc-timegrid-slot-label-cushion').allTextContents().then(x=>x.every(s=>!/am|pm/i.test(s))));ok('explicit Monday override',await p.locator('.fc-col-header-cell[data-date]').first().getAttribute('data-date')==='2026-10-05');await p.screenshot({path:'qa/date-picker-refresh/event-formats.png'});
 await go('page=event-calendar&calTab=playground&calDate=2026-10-05&calView=week&dateLocale=en-US&timeFormat=12&weekStart=1');await p.setViewportSize({width:390,height:844});await p.locator('.cal-agenda').waitFor();ok('mobile agenda honors 12-hour format',/AM|PM/i.test(await p.locator('.cal-agenda').innerText()));await p.screenshot({path:'qa/date-picker-refresh/mobile-formats.png'});await p.getByRole('button',{name:'Formats',exact:true}).click();ok('mobile format settings fit',await settings.evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth+1}));await p.keyboard.press('Escape');
 await go('page=event-calendar&calTab=integration');await p.getByRole('link',{name:'Download components',exact:true}).waitFor();ok('emailed integration URL opens integration',true);await go('page=event-calendar&calTab=usage');await p.getByRole('link',{name:'Download components',exact:true}).waitFor();ok('legacy integration URL retained',true);
 ok('no formatting errors',errors.length===0);console.log(JSON.stringify({passed:checks.length,errors}));
}catch(e){console.error(e);await p.screenshot({path:'qa/date-picker-refresh/formats-failure.png'});process.exitCode=1}finally{fs.writeFileSync('qa/date-picker-refresh/formats-report.json',JSON.stringify({checks,errors,at:new Date().toISOString()},null,2));await b.close()}
