import {chromium} from 'playwright';
import fs from 'node:fs';
const base=process.env.DEMO_URL||'http://127.0.0.1:5198';
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1600,height:1000},reducedMotion:'reduce'});
const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
function ok(name,value){checks.push({name,passed:!!value});if(!value)throw Error(name)}
await page.goto(base);await page.locator('.recharts-surface').first().waitFor();ok('ten gallery charts',await page.locator('.recharts-surface').count()===10);await page.screenshot({path:'qa/gallery-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Polar',exact:true}).click();ok('polar filter',await page.locator('.gallery-item').count()===4);await page.getByRole('button',{name:'All charts',exact:true}).click();await page.getByLabel('Search widgets').fill('contributor');ok('search',await page.locator('.gallery-item').count()===1);await page.getByLabel('Search widgets').fill('');
await page.getByRole('button',{name:'Explore Traffic over time',exact:true}).click();ok('detail URL',page.url().includes('widget=area'));
await page.getByLabel('Width',{exact:true}).selectOption('12');await page.getByLabel('Height',{exact:true}).selectOption('624');ok('height control',Math.round((await page.locator('.widget-frame').boundingBox()).height)===624);
await page.getByRole('tab',{name:'Configuration',exact:true}).click();ok('JSON config reflects dimensions',(await page.locator('pre').textContent()).includes('624'));
const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Get configuration'}).click();const download=await dl;await download.saveAs('qa/downloaded-config.json');ok('JSON download',JSON.parse(fs.readFileSync('qa/downloaded-config.json')).layout.height===624);
await page.getByRole('tab',{name:'Data',exact:true}).click();ok('data rows',await page.locator('tbody tr').count()===30);await page.getByLabel('Period',{exact:true}).selectOption('7');ok('period changes data',await page.locator('tbody tr').count()===7);
await page.getByRole('tab',{name:'Preview',exact:true}).click();await page.getByLabel('State',{exact:true}).selectOption('error');await page.getByRole('button',{name:'Try again',exact:true}).click();ok('retry',await page.getByLabel('State',{exact:true}).inputValue()==='ready');await page.getByLabel('State',{exact:true}).selectOption('loading');ok('loading',await page.getByText('Loading sample data').isVisible());await page.getByLabel('State',{exact:true}).selectOption('empty');ok('empty',await page.getByText('No data in this period').isVisible());await page.getByLabel('State',{exact:true}).selectOption('ready');
const before=page.url();await page.getByRole('button',{name:'editorial theme',exact:true}).click();ok('theme changes',await page.locator('html').getAttribute('data-brand')==='editorial');await page.goBack();ok('back restores theme',page.url()===before&&await page.locator('html').getAttribute('data-brand')==='fabric');await page.goForward();ok('forward restores theme',await page.locator('html').getAttribute('data-brand')==='editorial');
for(const theme of ['fabric','editorial','terminal']){await page.goto(`${base}/?page=gallery&theme=${theme}`);await page.locator('.recharts-surface').first().waitFor();ok(`${theme} ten charts`,await page.locator('.recharts-surface').count()===10);await page.screenshot({path:`qa/theme-${theme}.png`,fullPage:true});}
for(const layout of ['overview','insight','polar']){await page.goto(`${base}/?page=layouts&layout=${layout}`);await page.locator('.recharts-surface').first().waitFor();ok(`layout ${layout}`,await page.locator('.recharts-surface').count()>0);if(layout==='insight'){const b=await page.locator('.widget-frame').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().bottom));ok('chart/table equal bottoms',Math.abs(b[0]-b[1])<1);ok('10 matching table rows',await page.locator('tbody tr').count()===10);}await page.screenshot({path:`qa/layout-${layout}.png`,fullPage:true});}
await page.goto(`${base}/?page=elements`);await page.getByRole('button',{name:'Create project',exact:true}).click();ok('button feedback',await page.getByRole('status').isVisible());await page.getByRole('switch').click();ok('switch',await page.getByRole('switch').getAttribute('aria-checked')==='false');await page.getByRole('tab',{name:'Activity',exact:true}).click();ok('element tabs',await page.getByText('Three components updated in this demo workspace.').isVisible());
for(const size of [1920,1280,390,320]){await page.setViewportSize({width:size,height:900});for(const route of ['gallery','layouts','elements','handoff','widget']){await page.goto(`${base}/?page=${route}&widget=radar&width=3`);await page.locator('h1').waitFor();ok(`${route} reflow ${size}`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await page.screenshot({path:`qa/radar-${size}.png`,fullPage:true});}
await page.setViewportSize({width:1600,height:1000});await page.goto(`${base}/?page=widget&widget=donut&width=6`);await page.locator('.recharts-surface').waitFor();await page.keyboard.press('Tab');ok('keyboard skip link',await page.locator('.skip').evaluate(e=>e===document.activeElement));await page.keyboard.press('Enter');ok('skip target',page.url().endsWith('#main'));
ok('no browser errors',errors.length===0);fs.writeFileSync('qa/browser-report.json',JSON.stringify({base,checkedAt:new Date().toISOString(),checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}));await browser.close();
